version: "3.7"
services:
  db:
    image: postgres:15
    container_name: db_app
    command: -p 1221
    expose:
      - 1221
    env_file:
      - .env

  backend:
    build:
      context: .
    env_file:
      - .env
    ports:
      - "9999:8000"
    depends_on:
      - db